export const LIST_CREATE 			= 'LIST_CREATE'
export const LIST_CREATE_SUCCESS 	= 'LIST_CREATE_SUCCESS'  
export const LIST_CREATE_ERROR 		= 'LIST_CREATE_ERROR'

export const LIST_UPDATE 			= 'LIST_UPDATE'
export const LIST_UPDATE_SUBMIT		= 'LIST_UPDATE_SUBMIT'
export const LIST_UPDATE_SUCCESS 	= 'LIST_UPDATE_SUCCESS'
export const LIST_UPDATE_ERROR 		= 'LIST_UPDATE_ERROR'

export const LIST_DELETE 			= 'LIST_DELETE'
export const LIST_DELETE_SUCCESS 	= 'LIST_DELETE_SUCCESS'
export const LIST_DELETE_ERROR 		= 'LIST_DELETE_ERROR'