export const BOARD_CREATE 			= 'BOARD_CREATE'
export const BOARD_CREATE_SUCCESS 	= 'BOARD_CREATE_SUCCESS'  
export const BOARD_CREATE_ERROR 	= 'BOARD_CREATE_ERROR'

export const BOARD_UPDATE 			= 'BOARD_UPDATE'
export const BOARD_UPDATE_SUBMIT	= 'BOARD_UPDATE_SUBMIT'
export const BOARD_UPDATE_SUCCESS 	= 'BOARD_UPDATE_SUCCESS'
export const BOARD_UPDATE_ERROR 	= 'BOARD_UPDATE_ERROR'

export const BOARD_DELETE 			= 'BOARD_DELETE'
export const BOARD_DELETE_SUCCESS 	= 'BOARD_DELETE_SUCCESS'
export const BOARD_DELETE_ERROR 	= 'BOARD_DELETE_ERROR'
