export const TEAM_SEND 					= 'TEAM_SEND'
export const TEAM_SEND_SUCCESS 			= 'TEAM_SEND_SUCCESS'
export const TEAM_SEND_NOT_FOUND		= 'TEAM_SEND_NOT_FOUND'
export const TEAM_SEND_ERROR 			= 'TEAM_SEND_ERROR'

export const TEAM_SEND_CANCEL 			= 'TEAM_SEND_CANCEL'
export const TEAM_SEND_CANCEL_SUCCESS 	= 'TEAM_SEND_CANCEL_SUCCESS'
export const TEAM_SEND_CANCEL_ERROR 	= 'TEAM_SEND_CANCEL_ERROR'

export const TEAM_ACCEPT 				= 'TEAM_ACCEPT'
export const TEAM_ACCEPT_SUCCESS 		= 'TEAM_ACCEPT_SUCCESS'
export const TEAM_ACCEPT_ERROR 			= 'TEAM_ACCEPT_ERROR'

export const TEAM_DECLINE 				= 'TEAM_DECLINE'
export const TEAM_DECLINE_SUCCESS 		= 'TEAM_DECLINE_SUCCESS'
export const TEAM_DECLINE_ERROR 		= 'TEAM_DECLINE_ERROR'

export const TEAM_REMOVE				= 'TEAM_REMOVE'
export const TEAM_REMOVE_SUCCESS		= 'TEAM_REMOVE_SUCCESS'
export const TEAM_REMOVE_ERROR			= 'TEAM_REMOVE_ERROR'