export const CARD_CREATE 			= 'CARD_CREATE'
export const CARD_CREATE_SUCCESS 	= 'CARD_CREATE_SUCCESS'  
export const CARD_CREATE_ERROR 		= 'CARD_CREATE_ERROR'

export const CARD_UPDATE 			= 'CARD_UPDATE'
export const CARD_UPDATE_SUBMIT		= 'CARD_UPDATE_SUBMIT'
export const CARD_UPDATE_SUCCESS 	= 'CARD_UPDATE_SUCCESS'
export const CARD_UPDATE_ERROR 		= 'CARD_UPDATE_ERROR'

export const CARD_DELETE 			= 'CARD_DELETE'
export const CARD_DELETE_SUCCESS 	= 'CARD_DELETE_SUCCESS'
export const CARD_DELETE_ERROR 		= 'CARD_DELETE_ERROR'
